Stats refactoring
ApeSwapFinance/apeswap-api pull request #12
Opened 2021-03-30 04:36 UTC by curiousMonkeyGeorge

- Implement single token staking incentivized Pools
- Refactor some Promise.all
- Refactor price getting into separate service (price.service.ts) and remove bsc_helpers.ts

2021-04-01 16:40 UTC, ape-swap requested changes
Small change to enhance the pricing service

2021-04-01 16:40 UTC, ape-swap commented on src/stats/price.service.ts
> +import { coinGeckoTokens } from 'src/utils/coinGeckoTokens';
Could we make these two files part of the service?

2021-04-02 04:59 UTC, curiousMonkeyGeorge commented on src/stats/price.service.ts
> +import { coinGeckoTokens } from 'src/utils/coinGeckoTokens';
done

2021-04-05 01:19 UTC, ape-swap requested changes
Excellent work! Left some small reviews and recommendations. 

Let me know if you have any question.

2021-04-05 01:19 UTC, ape-swap commented on src/stats/price.service.ts
> +];
I believe it would be cleaner to incorporate this to the PriceService class instead of making them isolated functions and variables.

2021-04-05 01:19 UTC, ape-swap commented on src/stats/price.service.ts
> +const chunk = (arr, n) =>
Look if this works as a possible replacement for this helper function
https://lodash.com/docs/#chunk

2021-04-05 01:19 UTC, ape-swap commented on src/stats/price.service.spec.ts
> +    const { prices } = await service.getTokenPrices();
I would be nice to write expect statements for all the key properties this function should return

2021-04-05 03:45 UTC, curiousMonkeyGeorge commented on src/stats/price.service.ts
> +];
done

2021-04-05 04:35 UTC, curiousMonkeyGeorge commented on src/stats/price.service.ts
> +const chunk = (arr, n) =>
done

2021-04-05 04:53 UTC, curiousMonkeyGeorge commented on src/stats/price.service.spec.ts
> +    const { prices } = await service.getTokenPrices();
I added something, let me know if you think it should be improved. Because prices returns an object of the form: 
`{
  tokenAddress1: { usd: 123 },
  tokenAddress2: { usd: 456 }
}`

I just added the expect for each tokenAddress to have a 'usd' property

2021-04-06 19:06 UTC, ape-swap approved these changes
Looks good!

2021-04-06 19:07 UTC, merged