Feat/external pools
ApeSwapFinance/apeswap-api pull request #221
Opened 2021-09-17 17:19 UTC by ixm-759

2021-09-18 00:11 UTC, ape-swap requested changes
Great work!

Remember to remove the old code. I also left some comments

2021-09-18 00:11 UTC, ape-swap commented on src/stats/stats.service.ts
> +        'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-yields/main/config/pools.json',
Lets make this configurable.

2021-09-18 00:11 UTC, ape-swap commented on src/stats/stats.service.ts
> +    await this.cacheManager.set('pools', pools, { ttl: 300 });
Do we need cache on this layer? 

If so maybe we can lower it so we can test the API quicker. As all the caches start to add up

2021-09-21 01:34 UTC, ixm-759 commented on src/stats/stats.service.ts
> +        'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-yields/main/config/pools.json',
An environment variable was added, it must be added in each POOL_LIST_URL environment

2021-09-21 01:37 UTC, ixm-759 commented on src/stats/stats.service.ts
> +    await this.cacheManager.set('pools', pools, { ttl: 300 });
The cache was removed, since at the end of the day the method is inside another in which cache is already applied.

2021-11-19 00:15 UTC, merged