feat: Bitquery module.
ApeSwapFinance/apeswap-api pull request #286
Opened 2022-01-25 22:14 UTC by ixm-759

2022-02-04 23:09 UTC, ape-swap requested changes
Very good work!  Left a few comments on the code. 

Also please remember to add `Dto` as a sufix of the new Dtos to follow that nomenclature.

2022-02-04 23:09 UTC, ape-swap commented on src/stats/stats.service.ts
> -    const circulatingSupply = totalSupply - burntAmount;
Lets keep using RPC whenever its possible and makes sense. It is more real time and precise.

2022-02-04 23:09 UTC, ape-swap commented on src/stats/stats.service.ts
> -    const circulatingSupply = totalSupply - treasuryAmount;
Lets keep using RPC whenever its possible and makes sense. It is more real time and precise.

2022-02-05 00:18 UTC, ixm-759 commented on src/bitquery/bitquery.controller.ts
> +  ): Promise<any> {
Done!

2022-02-05 00:18 UTC, ixm-759 commented on src/bitquery/bitquery.service.ts
> +      minTrade = minTrade || 0;
Done!

2022-02-05 00:18 UTC, ixm-759 commented on src/bitquery/dto/candle.dto.ts
> +export class CandleOptions {
Done!

2022-02-05 00:18 UTC, ixm-759 commented on src/bitquery/dto/pairInformation.dto.ts
> +}
Done!

2022-02-05 00:18 UTC, ixm-759 commented on src/stats/stats.service.ts
> -    const circulatingSupply = totalSupply - burntAmount;
Rollback! Done!

2022-02-05 00:19 UTC, ixm-759 commented on src/stats/stats.service.ts
> -    const circulatingSupply = totalSupply - treasuryAmount;
Rollback! Done!

2022-03-07 17:54 UTC, merged