Feat/stats without subgraph
ApeSwapFinance/apeswap-api pull request #289
Opened 2022-02-18 03:09 UTC by ixm-759

2022-02-25 22:26 UTC, ape-swap requested changes
Good job Casor! I just left some comments for potential refactors, specially about how the config object is being used instead of leveraging its service.  

You should refactor to use the `ChainConfigService` or just the vanilla NestJs config objects.

You can also consider this module for Web3 so we can deprecate the utils

2022-02-25 22:26 UTC, ape-swap commented on src/stats/price.service.ts
> +import configuration from 'src/config/configuration';
Please look into the lotterly module to look into how to properly use the configuration service.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/price.service.ts
> +    if (+chainId === +configuration().networksId.BSC) {
This is not meant to be used like this.

With proper instantiation you get properties like this

```javascript
   this.configService.get<number>('networkId.BSC');
```

2022-02-25 22:26 UTC, ape-swap commented on src/stats/price.service.ts
> +  private readonly TOKEN_LIST_URL = process.env.TOKEN_LIST_URL;
Can we add the token list URL to the configuration file instead and bring it from there?

2022-02-25 22:26 UTC, ape-swap commented on src/stats/price.service.ts
> +        usd: prices[bananaAddressNetwork(chainId)].usd / 0.72,
Lets stop using these methods that workaround how the framework is supposed to work. BANANA address should be fetched like this:

```javascript
const bananaAddress = this.configService.get<string>(`${chainId}.contracts.banana`);

```

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +import configuration from 'src/config/configuration';
This is not how the configuration is supposed to be imported. Please refactor

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +  private readonly DUAL_FARMS_LIST_URL = process.env.DUAL_FARMS_LIST_URL;
Could we move this information to the configuration object?

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +    private statsService: StatsService,
Here is where you import the configuration service. Look into examples or the lottery module for more clarity.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +      const priceUSD = prices[bananaAddressNetwork(chainId)].usd;
Lets use a proper configuration getter method instead of this one that doesn't properly leverage the service.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +        chainId: +chainId,
chainId should already be number here as per the specified type

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +  async getStatsNetwork(chainId: number): Promise<any> {
Could we typesafe the return value?

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +        case configuration().networksId.BSC:
Refactor to properly use the configuration service.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +      switch (+chainId) {
chainId should be a number by now or converted to a number earlier during the execution to avoid constatly using it as `+chainId` through the whole solution.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +    const miniChefAddress = masterApeContractAddressNetwork(chainId);
Lets access the configutation using the recommended methods.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/utils/stats.utils.ts
> +
This isn't meant to be used like this. It was just a workaround because this file was never instantiated as a service that could leverage the NestJS configuration service. Lets abandon this pattern and stop building on top of it ASAP.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/utils/stats.utils.ts
>  }
The previous comment applies to all of these.

2022-02-25 22:26 UTC, ape-swap commented on src/stats/stats.service.ts
> +    const bananaAddress = bananaAddressNetwork(chainId);
This should be switched in favour of leveraging the ConfigurationService

2022-02-25 22:26 UTC, ape-swap commented on src/stats/utils/dualFarms.ts
> +const dualFarms: any[] = [
Should we place this in the yields repo?

2022-02-26 03:38 UTC, ixm-759 commented on src/stats/stats.network.service.ts
> +      switch (+chainId) {
It was adjusted so that from the controller it sends it in this way and so it is already as integer. I hope it is a good solution

2022-02-26 03:40 UTC, ixm-759 commented on src/stats/utils/dualFarms.ts
> +const dualFarms: any[] = [
This file was for testing, I forgot to delete it. Replaced with the logic of getting farms from the `**apeswap-yield**` repository. It was already removed

2022-03-07 17:00 UTC, ape-swap approved these changes
Looking good! 

Thanks for the changes and refactors.

`src/stats/utils/stats.utils.ts` is looking a bit 'heavy' at present. 

We will need to discuss how to refactor it down the road.

2022-03-07 17:54 UTC, merged