Fix/subgraph apr
ApeSwapFinance/apeswap-api pull request #300
Opened 2022-03-17 18:03 UTC by ixm-759

2022-03-18 17:25 UTC, ape-swap requested changes
- Please typesafe every function by default.
- Please when applicable return semantic object structure from functions, not arrays.
- Would be great to refactor the `subgraph.service.ts` file into smaller chunk functions, create a separate file or both. 

Let me know if you have any questions or concerns.

2022-03-18 17:25 UTC, ape-swap commented on src/stats/subgraph.service.ts
> +  async getEthPrice(chainId) {
Could you typesafe this function and use a more semantic name? 

Even though the Subgraph calls the protocol-token ETH. Neither of our chains uses ETH.

2022-03-18 17:25 UTC, ape-swap commented on src/stats/subgraph.service.ts
> +    return [ethPrice, ethPriceOneDay, priceChangeETH];
Please. Return a typesafed object with semantic names on their properties.

This approach is not recommended and can easily grow out of control.

2022-03-18 17:25 UTC, ape-swap commented on src/stats/subgraph.service.ts
> +  }
I this needed or can we call `getBlocksFromTimestamps` with one timestamp?

2022-03-18 17:25 UTC, ape-swap commented on src/stats/subgraph.service.ts
> +  }
Is there a way to compartmentalize this into smaller chunks of more readeable code?

I would consider splitting some of this code on another file, relative to the responsabilities of the functions.

2022-03-18 17:25 UTC, ape-swap commented on src/utils/helpers.ts
> +}
Please typesafe this function and return a semantic object instead of an array.

2022-03-18 17:25 UTC, ape-swap commented on src/utils/helpers.ts
> +};
Please return typesafed semantic objects instead of arrays in instances like this.

2022-03-19 01:56 UTC, ixm-759 commented on src/stats/subgraph.service.ts
> +  async getEthPrice(chainId) {
Done!

2022-03-19 01:56 UTC, ixm-759 commented on src/stats/subgraph.service.ts
> +    return [ethPrice, ethPriceOneDay, priceChangeETH];
Done!

2022-03-19 01:57 UTC, ixm-759 commented on src/stats/subgraph.service.ts
> +  }
I eliminated this method and used another one that was already there but in bulk, I adapted it to the method I was using.

2022-03-19 01:58 UTC, ixm-759 commented on src/stats/subgraph.service.ts
> +  }
I split the method, making other methods more readable and easier to read.

2022-03-19 01:59 UTC, ixm-759 commented on src/utils/helpers.ts
> +}
Done!

2022-03-19 01:59 UTC, ixm-759 commented on src/utils/helpers.ts
> +};
Done!

2022-03-21 20:38 UTC, ape-swap approved these changes
Nice refactor! Thanks

2022-03-21 20:42 UTC, merged