Feat/dashboard data
ApeSwapFinance/apeswap-api pull request #345
Opened 2022-07-14 23:02 UTC by ixm-759

2022-07-15 16:32 UTC, ape-swap requested changes
Thanks for the work Casor! Leaving some comments for improvements

2022-07-15 16:32 UTC, ape-swap commented on src/dashboard/dashboard.module.ts
> +    forwardRef(() => BitqueryModule),
I struggle to understand the need of this forwardRef, could you elaborate on it?

2022-07-15 16:32 UTC, ape-swap commented on src/dashboard/dashboard.module.ts
> +  providers: [DashboardService, ChainConfigService, SubgraphService, PriceService],
This feels off to me. You should import the respective modules in the `imports` array, instead of using forward ref at app level and having access to everything of the whole app.

2022-07-15 16:32 UTC, ape-swap commented on src/dashboard/dashboard.service.ts
> +  private readonly BILL_TREASURY_WALLET = '0x944694417A6cA0a70963D644A11d42C10e3af042';
Could we move this to the config file?

2022-07-15 16:32 UTC, ape-swap commented on src/dashboard/helpers.ts
> +export function mappingCurrencies(lpInformation: any): string[] {
Please typesafe the input parameter

2022-07-15 17:32 UTC, ixm-759 commented on src/dashboard/dashboard.module.ts
> +  providers: [DashboardService, ChainConfigService, SubgraphService, PriceService],
Those 3 services (Chain, Subgraph, Price) are direct services and have no module. They are found in `stats.service` and are listed as Providers

https://github.com/ApeSwapFinance/apeswap-api/blob/feat/dashboard_data/src/stats/stats.module.ts#L35

2022-07-20 21:04 UTC, ixm-759 commented on src/app.module.ts
> +    forwardRef(() => DashboardModule),
Done!

2022-07-20 21:04 UTC, ixm-759 commented on src/dashboard/dashboard.module.ts
> +    forwardRef(() => BitqueryModule),
Done!

2022-07-20 21:04 UTC, ixm-759 commented on src/dashboard/dashboard.module.ts
> +  providers: [DashboardService, ChainConfigService, SubgraphService, PriceService],
Done!

2022-07-20 21:04 UTC, ixm-759 commented on src/dashboard/dashboard.service.ts
> +  private readonly BILL_TREASURY_WALLET = '0x944694417A6cA0a70963D644A11d42C10e3af042';
Done!

2022-07-20 21:04 UTC, ixm-759 commented on src/dashboard/helpers.ts
> +export function mappingCurrencies(lpInformation: any): string[] {
Done!

2022-08-29 23:38 UTC, ape-swap requested changes
Good work ser!

I left several inline comments in addition to that I have the following observations:

- There seem to be some redundancies in the cache layer, the value added of the combination with memory cache with Database Cache is not clear. In addition the nestJS cache library installed can do full response caching out of the box, potentially allowing to trim a lot lines of code: https://docs.nestjs.com/techniques/caching#auto-caching-responses
- There are many `any` declarations and more importantly functions without adecuate response type. Please typesafe those.
- Please remove all awaits from within loops.

2022-08-29 23:38 UTC, ape-swap commented on src/stats/price.service.ts
> +    // }
Please delete unused code

2022-08-29 23:38 UTC, ape-swap commented on src/stats/stats.network.service.ts
> +              //this.statsService.mappingIncetivizedPools(generalStats, prices),
Please remove unused code

2022-08-30 16:08 UTC, merged