Feat/multi chain bills
ApeSwapFinance/apeswap-api pull request #361
Opened 2022-08-31 19:51 UTC by Prof-SD

2022-09-16 17:02 UTC, Apegurus commented on src/bills/bills.images.service.ts
> +    )
I think this change made me spot a bug I introduced. Maybe we could document it or fix it here if we think its a low hanging fruit. 

I believe that since we updated our NFT contract, this code would regenerate in V1 format NFTs with tokenIds lower than 450 from the new contract, which is not what was originally intended here.

2022-09-16 17:03 UTC, Apegurus commented on src/bills/bills.images.service.ts
> +    )
lol, false. Disregard.

2022-09-16 17:20 UTC, Apegurus requested changes
Elegant and smooth enhancement! Great job. 

Only observation is changing all instances of 56 and 137 to Network.bsc and Network.polygon enums respectively.

2022-09-16 17:20 UTC, Apegurus commented on src/bills/schema/billsMetadata.schema.ts
> +  @Prop({ required: true })
There is currently a bug/race condition that generates duplicity in the DB if this one is not marked as unique index. @casor6  is working on the fix. Worth keeping this in mind

2022-09-19 16:24 UTC, Prof-SD commented on src/bills/schema/billsMetadata.schema.ts
> +  @Prop({ required: true })
I'll link up with @casor6 on this, but we can't have this unique because every new chain starts the ids for this at 0 again. Bringing in chainId and using the the _id column as the unique field should fix this though (I think, but will confirm with Casor)

2022-09-20 18:36 UTC, merged