Feat/bills summary v2
ApeSwapFinance/apeswap-api pull request #365
Opened 2022-09-02 19:37 UTC by ixm-759

2022-09-02 23:58 UTC, ape-swap approved these changes
Looks good to me!

2022-10-01 05:11 UTC, Apegurus requested changes
Hey! It mostly looks good, I just struggle to understand why do we remove the type safe from the chainId function parameter.

2022-10-01 05:11 UTC, Apegurus commented on src/bills/bills.service.ts
> +  async getBillDataFromTransaction(transactionHash: string, chainId = 56) {
This doesn't look right.

2022-10-01 05:11 UTC, Apegurus commented on src/bills/bills.service.ts
> +  async getBillTerms(contractAddress: string, chainId = 56): Promise<BillTerms> {
This doesn't look right. Why are we removing the typings?

2022-10-07 07:14 UTC, Apegurus commented on src/bills/bills.service.ts
> +  async getBillTerms(contractAddress: string, chainId = 56): Promise<BillTerms> {
Got it, thanks for the clarification!

2022-10-07 08:07 UTC, Apegurus requested changes
Casor, for your own good, please review your own code and changes before asking for a reviewer on the PR. Many of the issues I identified should have been catch before this reached me. 

I observe a big lack of error handling strategies and feel that there is a general miss-understanding on how this could be used to add value, when submitting code I need you to take time to think through why are you making some of these decisions and if they actually add any meaningful value to the stability or readability of the codebase or if they are just workarounds. 

Would you be able to look more into this and take extra time to review your code to make sure everything is in its best place before submitting?

2022-10-11 00:12 UTC, ixm-759 commented on src/bills/bills.service.ts
> +    private subgraphService: SubgraphService,
Removed unused code.

2022-10-11 00:16 UTC, ixm-759 commented on src/bills/bills.module.ts
> +      { name: TokenBitquery.name, schema: TokenBitquerySchema },
The way I was importing the bitquery service, I needed this data to be in the import as well.
I have imported the module so that it is no longer used in this way.

2022-10-11 00:17 UTC, ixm-759 commented on src/bills/bills.service.ts
> +      const resultPrices = await Promise.all(promisePrices);
Refactored

2022-10-11 00:17 UTC, ixm-759 commented on src/bills/interface/billData.interface.ts
> +  createdAt?: string;
Fixed

2022-10-11 00:29 UTC, ixm-759 commented on src/bitquery/bitquery.service.ts
> +    }
The way in which the data is being returned is by destructuring the information, in case no information is obtained it would send an error, this would affect the execution of the batch of promises if one had an error and the others would no longer be updated.
Add a trycatch so it doesn't affect the batch.

https://github.com/ApeSwapFinance/apeswap-api/pull/365/files#diff-c9d3870cd36ba65f1d5409896702f0b6b54dd268011fb2f82097305fcb8ec4b6R360

2022-10-11 00:34 UTC, ixm-759 commented on src/dashboard/dashboardHistoryHelper.service.ts
> +    private priceService: PriceService,
When the staging pull was made, it made changes to this file, if the service is used, it will be fixed.

2022-10-11 00:36 UTC, ixm-759 commented on src/stats/price.service.ts
> +  }
Apparently it complicated the way to obtain the prices, it was occupying that extra information in case the price is not obtained directly from the subgraph and it happens to obtain it from bitquery, and that is where that information is occupied.
I've refactored this so that it only receives simpler values to get the price.

The type of data that is returned was also added.

2022-10-11 00:37 UTC, ixm-759 commented on src/stats/subgraph.service.ts
> +    }
Refactored

2022-10-17 21:01 UTC, Apegurus requested changes
Thanks for the work Casor!

Please look into:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

As an alternative Promise.all when you don't want the batch to halt execution. This will greatly help with your error handling practices that are workarounds to Promise.all and not ideal error handling. 

Please also look into the couple of comments I left

2022-12-01 00:26 UTC, Apegurus requested changes
Thank you for the work. 

Comments provided!

2022-12-01 00:26 UTC, Apegurus commented on src/bills/bills.service.ts
> +    const { data } = await this.httpService.get(this.config.get<string>('billListUrl')).toPromise();
You can cache this in memory under a normal variable on this same class or using NestJSs cache service that is used within this repo. 

I don't believe the HTTP request is needed every single time we call this function.

2022-12-01 00:26 UTC, Apegurus commented on src/stats/price.service.ts
> +    limit = 1,
When you removed the default value from currency you made the defaults from block and timestamp unusable, as you will always need to put those parameters to fullfil the required parameter of currency. 

Please pay more attention to detail.

I also still don't understand when, how or why would you call this function with block = 0 or timestamp = null

2022-12-14 18:10 UTC, Apegurus approved these changes

2022-12-15 01:57 UTC, merged