feature/pools_strapi
ApeSwapFinance/apeswap-api pull request #73
Opened 2021-05-21 23:39 UTC by ixm-759

feat: fetch pools from strapi

2021-05-22 23:32 UTC, ape-swap requested changes
Could we add a cache layer so it does not have to do the request every time?

2021-05-24 15:54 UTC, ixm-759 commented
This service is part of the main method that is already handled with a cache and runs again every 5 minutes, so it would be called every 5 minutes.

2021-05-26 02:03 UTC, DeFiFoFum approved these changes

2021-05-30 19:38 UTC, ape-swap approved these changes

2021-05-30 19:38 UTC, merged